server {
    if ($host = {{ host }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
    server_name {{ host }};
    return 301 https://$host$request_uri;
}

server {
    if ($host = www.{{ host }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
    server_name www.{{ host }};
    return 301 https://{{ host }}$request_uri;
}

server {
    listen 443 ;
    listen [::]:443 ;
    server_name www.{{ host }};
    # Redirect to a domain without www
    return 301 https://{{ host }}$request_uri;

    {{#ssl-certificate}}ssl_certificate {{ssl-certificate}};{{/ssl-certificate}}
    {{#ssl-certificate-key}}ssl_certificate_key {{ssl-certificate}};{{/ssl-certificate-key}}
}


server {
    root /var/www/html/{{ host }};
    server_name {{ host }}; # managed by Certbot

    location /static/ {
      root /var/www/html/{{ host }};
    }

    location / {
      limit_req zone=mylimit burst=10;

      proxy_pass http://localhost:{{ backend-port }};
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_pass_request_headers on;
    }

    listen 443 ssl; # managed by Certbot
    {{#ssl-certificate}}ssl_certificate {{ssl-certificate}};{{/ssl-certificate}}
    {{#ssl-certificate-key}}ssl_certificate_key {{ssl-certificate}};{{/ssl-certificate-key}}
}
