server {
    if ($host = {{ host }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
    server_name {{ host }};
    return 301 https://$host$request_uri;
}

server {
    if ($host = www.{{ host }}) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
    server_name www.{{ host }};
    return 301 https://{{ host }}$request_uri;
}

server {
    server_name www.{{ host }};
    # Redirect to a domain without www
    return 301 https://{{ host }}$request_uri;

    {{#ssl-certificate}}listen 443 ssl; # managed by Certbot{{/ssl-certificate}}
    {{#ssl-certificate}}ssl_certificate {{ssl-certificate}}; # managed by Certbot{{/ssl-certificate}}
    {{#ssl-certificate-key}}ssl_certificate_key {{ssl-certificate-key}}; # managed by Certbot{{/ssl-certificate-key}}

}


server {
    root /var/www/html/{{ host }};
    server_name {{ host }}; # managed by Certbot

{{#routes}}
{{>*type}}
{{/routes}}

    {{#ssl-certificate}}listen 443 ssl; # managed by Certbot{{/ssl-certificate}}
    {{#ssl-certificate}}ssl_certificate {{ssl-certificate}}; # managed by Certbot{{/ssl-certificate}}
    {{#ssl-certificate-key}}ssl_certificate_key {{ssl-certificate-key}}; # managed by Certbot{{/ssl-certificate-key}}

}
